spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo1
    username: root
    password: root
    druid:
      min-idle: 3
      max-active: 10
      max-wait: 2600
      filter: stat wall
      time-between-eviction-runs-millis: 5000
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: site.liangchen.demo1.pojo
  global-config:
    db-config:
      id-type: auto
      db-type: mysql
    refresh: true




